export const products = [
  {
    id: 1,
    name: "Organic Tomatoes",
    description: "Fresh, juicy organic tomatoes perfect for salads, cooking, and sauces. Grown without pesticides.",
    price: 4.99,
    unit: "lb",
    category: "Vegetables",
    image: "/images/organic-tomatoes.jpg",
    inStock: true,
  },
  {
    id: 2,
    name: "Fresh Carrots",
    description: "Crisp and sweet carrots, perfect for snacking, cooking, or juicing. Rich in beta-carotene.",
    price: 2.99,
    unit: "lb",
    category: "Vegetables",
    image: "/images/fresh-carrots.jpg",
    inStock: true,
  },
  {
    id: 3,
    name: "Green Spinach",
    description: "Nutrient-rich spinach leaves, perfect for salads, smoothies, and cooking. High in iron and vitamins.",
    price: 3.49,
    unit: "bunch",
    category: "Vegetables",
    image: "/images/green-spinach.jpg",
    inStock: true,
  },
  {
    id: 4,
    name: "Red Bell Peppers",
    description: "Sweet and crunchy red bell peppers, great for cooking, grilling, or eating raw.",
    price: 5.99,
    unit: "lb",
    category: "Vegetables",
    image: "/images/red-bell-peppers.jpg",
    inStock: true,
  },
  {
    id: 5,
    name: "Fresh Broccoli",
    description: "Green, nutritious broccoli crowns perfect for steaming, roasting, or stir-frying.",
    price: 3.99,
    unit: "head",
    category: "Vegetables",
    image: "/images/fresh-broccoli.jpg",
    inStock: true,
  },
  {
    id: 6,
    name: "Organic Apples",
    description: "Crisp and sweet organic apples, perfect for snacking or baking. Variety of flavors available.",
    price: 4.49,
    unit: "lb",
    category: "Fruits",
    image: "/images/organic-apples.jpg",
    inStock: true,
  },
  {
    id: 7,
    name: "Fresh Bananas",
    description: "Ripe, sweet bananas perfect for breakfast, smoothies, or baking. Rich in potassium.",
    price: 1.99,
    unit: "lb",
    category: "Fruits",
    image: "/images/fresh-bananas.jpg",
    inStock: true,
  },
  {
    id: 8,
    name: "Juicy Oranges",
    description: "Sweet and juicy oranges, perfect for fresh juice or snacking. High in vitamin C.",
    price: 3.99,
    unit: "lb",
    category: "Fruits",
    image: "/images/juicy-oranges.jpg",
    inStock: true,
  },
  {
    id: 9,
    name: "Fresh Strawberries",
    description: "Sweet, juicy strawberries perfect for desserts, smoothies, or eating fresh.",
    price: 6.99,
    unit: "pint",
    category: "Fruits",
    image: "/images/fresh-strawberries.jpg",
    inStock: true,
  },
  {
    id: 10,
    name: "Ripe Avocados",
    description: "Creamy, ripe avocados perfect for guacamole, toast, or salads. Rich in healthy fats.",
    price: 2.49,
    unit: "each",
    category: "Fruits",
    image: "/images/ripe-avocados.jpg",
    inStock: true,
  },
  {
    id: 11,
    name: "Organic Brown Rice",
    description: "Nutritious whole grain brown rice, perfect for healthy meals. High in fiber and nutrients.",
    price: 8.99,
    unit: "5lb bag",
    category: "Grains",
    image: "/images/organic-brown-rice.jpg",
    inStock: true,
  },
  {
    id: 12,
    name: "Quinoa",
    description: "Protein-rich quinoa, a superfood grain perfect for salads, bowls, and side dishes.",
    price: 12.99,
    unit: "2lb bag",
    category: "Grains",
    image: "/images/quinoa.jpg",
    inStock: true,
  },
  {
    id: 13,
    name: "Whole Wheat Flour",
    description: "Stone-ground whole wheat flour, perfect for baking bread, pastries, and other baked goods.",
    price: 6.49,
    unit: "5lb bag",
    category: "Grains",
    image: "/images/whole-wheat-flour.jpg",
    inStock: true,
  },
  {
    id: 14,
    name: "Rolled Oats",
    description: "Hearty rolled oats perfect for breakfast, baking, and healthy snacks. High in fiber.",
    price: 4.99,
    unit: "3lb bag",
    category: "Grains",
    image: "/images/rolled-oats.jpg",
    inStock: true,
  },
  {
    id: 15,
    name: "Fresh Basil",
    description: "Aromatic fresh basil leaves, perfect for cooking, garnishing, and making pesto.",
    price: 2.99,
    unit: "bunch",
    category: "Herbs",
    image: "/images/fresh-basil.jpg",
    inStock: true,
  },
  {
    id: 16,
    name: "Organic Cilantro",
    description: "Fresh cilantro with a bright, citrusy flavor perfect for Mexican and Asian dishes.",
    price: 1.99,
    unit: "bunch",
    category: "Herbs",
    image: "/images/organic-cilantro.jpg",
    inStock: true,
  },
  {
    id: 17,
    name: "Fresh Rosemary",
    description: "Fragrant rosemary sprigs perfect for roasting, grilling, and seasoning meats and vegetables.",
    price: 3.49,
    unit: "bunch",
    category: "Herbs",
    image: "/images/fresh-rosemary.jpg",
    inStock: true,
  },
  {
    id: 18,
    name: "Fresh Thyme",
    description: "Delicate thyme leaves with an earthy flavor, perfect for soups, stews, and marinades.",
    price: 2.79,
    unit: "bunch",
    category: "Herbs",
    image: "/images/fresh-thyme.jpg",
    inStock: true,
  },
]
